// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: address.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO address (
    country,
    city,
    street
) VALUES (
    $1, $2, $3
)
RETURNING id, country, city, street, created_at, updated_at
`

type CreateAddressParams struct {
	Country string `json:"country"`
	City    string `json:"city"`
	Street  string `json:"street"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress, arg.Country, arg.City, arg.Street)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Country,
		&i.City,
		&i.Street,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, country, city, street, created_at, updated_at FROM address
WHERE id = $1
`

func (q *Queries) GetAddressByID(ctx context.Context, id uuid.UUID) (Address, error) {
	row := q.db.QueryRow(ctx, getAddressByID, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Country,
		&i.City,
		&i.Street,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
