// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createClient = `-- name: CreateClient :one
INSERT INTO client (
    client_name,
    client_surname,
    birthday,
    gender,
    address_id
)
VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, client_name, client_surname, birthday, gender, registration_date, address_id, updated_at
`

type CreateClientParams struct {
	ClientName    string     `json:"client_name"`
	ClientSurname string     `json:"client_surname"`
	Birthday      time.Time  `json:"birthday"`
	Gender        string     `json:"gender"`
	AddressID     *uuid.UUID `json:"address_id"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.ClientName,
		arg.ClientSurname,
		arg.Birthday,
		arg.Gender,
		arg.AddressID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.ClientSurname,
		&i.Birthday,
		&i.Gender,
		&i.RegistrationDate,
		&i.AddressID,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM client
WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const getAllClients = `-- name: GetAllClients :many
SELECT id, client_name, client_surname, birthday, gender, registration_date, address_id, updated_at FROM client ORDER BY registration_date
`

func (q *Queries) GetAllClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.Query(ctx, getAllClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.ClientName,
			&i.ClientSurname,
			&i.Birthday,
			&i.Gender,
			&i.RegistrationDate,
			&i.AddressID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, client_name, client_surname, birthday, gender, registration_date, address_id, updated_at from client
WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.ClientSurname,
		&i.Birthday,
		&i.Gender,
		&i.RegistrationDate,
		&i.AddressID,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientsByFullName = `-- name: GetClientsByFullName :many
SELECT id, client_name, client_surname, birthday, gender, registration_date, address_id, updated_at FROM client
WHERE client_name ILIKE $1 AND client_surname ILIKE $2
`

type GetClientsByFullNameParams struct {
	ClientName    string `json:"client_name"`
	ClientSurname string `json:"client_surname"`
}

func (q *Queries) GetClientsByFullName(ctx context.Context, arg GetClientsByFullNameParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, getClientsByFullName, arg.ClientName, arg.ClientSurname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.ClientName,
			&i.ClientSurname,
			&i.Birthday,
			&i.Gender,
			&i.RegistrationDate,
			&i.AddressID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientsWithPagination = `-- name: GetClientsWithPagination :many
SELECT id, client_name, client_surname, birthday, gender, registration_date, address_id, updated_at FROM client
ORDER BY registration_date
LIMIT $1 OFFSET $2
`

type GetClientsWithPaginationParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetClientsWithPagination(ctx context.Context, arg GetClientsWithPaginationParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, getClientsWithPagination, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.ClientName,
			&i.ClientSurname,
			&i.Birthday,
			&i.Gender,
			&i.RegistrationDate,
			&i.AddressID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClientAddress = `-- name: UpdateClientAddress :one
UPDATE client
SET address_id = $2
WHERE id = $1
RETURNING id, client_name, client_surname, birthday, gender, registration_date, address_id, updated_at
`

type UpdateClientAddressParams struct {
	ID        uuid.UUID `json:"id"`
	AddressID uuid.UUID `json:"address_id"`
}

func (q *Queries) UpdateClientAddress(ctx context.Context, arg UpdateClientAddressParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClientAddress, arg.ID, arg.AddressID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.ClientSurname,
		&i.Birthday,
		&i.Gender,
		&i.RegistrationDate,
		&i.AddressID,
		&i.UpdatedAt,
	)
	return i, err
}
