// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createImage = `-- name: CreateImage :one
INSERT INTO image (
    image_data,
    product_id
) VALUES (
    $1, $2
)
RETURNING id, image_data, product_id, created_at, updated_at
`

type CreateImageParams struct {
	ImageData []byte     `json:"image_data"`
	ProductID *uuid.UUID `json:"product_id"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage, arg.ImageData, arg.ProductID)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ImageData,
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteImageByID = `-- name: DeleteImageByID :exec
DELETE FROM image WHERE id = $1
`

func (q *Queries) DeleteImageByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteImageByID, id)
	return err
}

const getImageByImageId = `-- name: GetImageByImageId :one
SELECT id, image_data, product_id, created_at, updated_at FROM image
WHERE id = $1
`

func (q *Queries) GetImageByImageId(ctx context.Context, id uuid.UUID) (Image, error) {
	row := q.db.QueryRow(ctx, getImageByImageId, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ImageData,
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImageByProductID = `-- name: GetImageByProductID :many
SELECT id, image_data, product_id, created_at, updated_at FROM image
WHERE product_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetImageByProductID(ctx context.Context, productID uuid.UUID) ([]Image, error) {
	rows, err := q.db.Query(ctx, getImageByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.ImageData,
			&i.ProductID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImage = `-- name: UpdateImage :one
UPDATE image
SET image_data = $2
WHERE id = $1
RETURNING id, image_data, product_id, created_at, updated_at
`

type UpdateImageParams struct {
	ID        uuid.UUID `json:"id"`
	ImageData []byte    `json:"image_data"`
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, updateImage, arg.ID, arg.ImageData)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ImageData,
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
