// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Address struct {
	ID        uuid.UUID `json:"id"`
	Country   string    `json:"country"`
	City      string    `json:"city"`
	Street    string    `json:"street"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Category struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Client struct {
	ID               uuid.UUID `json:"id"`
	ClientName       string    `json:"client_name"`
	ClientSurname    string    `json:"client_surname"`
	Birthday         time.Time `json:"birthday"`
	Gender           string    `json:"gender"`
	RegistrationDate time.Time `json:"registration_date"`
	AddressID        uuid.UUID `json:"address_id"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Image struct {
	ID        uuid.UUID `json:"id"`
	ImageData []byte    `json:"image_data"`
	ProductID uuid.UUID `json:"product_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Product struct {
	ID                      uuid.UUID `json:"id"`
	Name                    string    `json:"name"`
	CategoryID              uuid.UUID `json:"category_id"`
	Price                   float64   `json:"price"`
	AvailableStock          int16     `json:"available_stock"`
	LastAvailableUpdateDate time.Time `json:"last_available_update_date"`
	SupplierID              uuid.UUID `json:"supplier_id"`
	CreatedAt               time.Time `json:"created_at"`
	UpdatedAt               time.Time `json:"updated_at"`
}

type Supplier struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	AddressID   uuid.UUID `json:"address_id"`
	PhoneNumber string    `json:"phone_number"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
