// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO product (
    name,
    category_id,
    price,
    available_stock,
    supplier_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, category_id, price, available_stock, last_available_update_date, supplier_id, created_at, updated_at
`

type CreateProductParams struct {
	Name           string    `json:"name"`
	CategoryID     uuid.UUID `json:"category_id"`
	Price          float64   `json:"price"`
	AvailableStock int16     `json:"available_stock"`
	SupplierID     uuid.UUID `json:"supplier_id"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.CategoryID,
		arg.Price,
		arg.AvailableStock,
		arg.SupplierID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Price,
		&i.AvailableStock,
		&i.LastAvailableUpdateDate,
		&i.SupplierID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decreaseProductStock = `-- name: DecreaseProductStock :one
UPDATE product
SET available_stock = available_stock - $2::SMALLINT
WHERE id = $1 
  AND available_stock >= $2::SMALLINT
RETURNING id, name, category_id, price, available_stock, last_available_update_date, supplier_id, created_at, updated_at
`

type DecreaseProductStockParams struct {
	ID            uuid.UUID `json:"id"`
	Decreasevalue int16     `json:"decreasevalue"`
}

func (q *Queries) DecreaseProductStock(ctx context.Context, arg DecreaseProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, decreaseProductStock, arg.ID, arg.Decreasevalue)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Price,
		&i.AvailableStock,
		&i.LastAvailableUpdateDate,
		&i.SupplierID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductByID = `-- name: DeleteProductByID :exec
DELETE FROM product WHERE id = $1
`

func (q *Queries) DeleteProductByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductByID, id)
	return err
}

const getAvailableProducts = `-- name: GetAvailableProducts :many
SELECT id, name, category_id, price, available_stock, last_available_update_date, supplier_id, created_at, updated_at FROM product
WHERE available_stock > 0
ORDER BY available_stock DESC
`

func (q *Queries) GetAvailableProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, getAvailableProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.Price,
			&i.AvailableStock,
			&i.LastAvailableUpdateDate,
			&i.SupplierID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, category_id, price, available_stock, last_available_update_date, supplier_id, created_at, updated_at FROM product WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Price,
		&i.AvailableStock,
		&i.LastAvailableUpdateDate,
		&i.SupplierID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const increaseProductStock = `-- name: IncreaseProductStock :one
UPDATE product
SET available_stock = available_stock + $2::SMALLINT
WHERE id = $1 
RETURNING id, name, category_id, price, available_stock, last_available_update_date, supplier_id, created_at, updated_at
`

type IncreaseProductStockParams struct {
	ID            uuid.UUID `json:"id"`
	Increasevalue int16     `json:"increasevalue"`
}

func (q *Queries) IncreaseProductStock(ctx context.Context, arg IncreaseProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, increaseProductStock, arg.ID, arg.Increasevalue)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.Price,
		&i.AvailableStock,
		&i.LastAvailableUpdateDate,
		&i.SupplierID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
