// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateImage(ctx context.Context, arg CreateImageParams) (Image, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	DecreaseProductStock(ctx context.Context, arg DecreaseProductStockParams) (Product, error)
	DeleteClient(ctx context.Context, id uuid.UUID) error
	DeleteImageByID(ctx context.Context, id uuid.UUID) error
	DeleteProductByID(ctx context.Context, id uuid.UUID) error
	DeleteSupplier(ctx context.Context, id uuid.UUID) error
	GetAddressByID(ctx context.Context, id uuid.UUID) (Address, error)
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetAllClients(ctx context.Context) ([]Client, error)
	GetAllSuppliers(ctx context.Context) ([]Supplier, error)
	GetAvailableProducts(ctx context.Context) ([]Product, error)
	GetClientByID(ctx context.Context, id uuid.UUID) (Client, error)
	GetClientsByFullName(ctx context.Context, arg GetClientsByFullNameParams) ([]Client, error)
	GetClientsWithPagination(ctx context.Context, arg GetClientsWithPaginationParams) ([]Client, error)
	GetImageByImageId(ctx context.Context, id uuid.UUID) (Image, error)
	GetImageByProductID(ctx context.Context, productID uuid.UUID) ([]Image, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	GetSupplierByID(ctx context.Context, id uuid.UUID) (Supplier, error)
	IncreaseProductStock(ctx context.Context, arg IncreaseProductStockParams) (Product, error)
	UpdateClientAddress(ctx context.Context, arg UpdateClientAddressParams) (Client, error)
	UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error)
	UpdateSupplierAddress(ctx context.Context, arg UpdateSupplierAddressParams) (Supplier, error)
}

var _ Querier = (*Queries)(nil)
