// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: supplier.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO supplier (
    name,
    address_id,
    phone_number
)
VALUES (
    $1, $2, $3
)
RETURNING id, name, address_id, phone_number, created_at, updated_at
`

type CreateSupplierParams struct {
	Name        string     `json:"name"`
	AddressID   *uuid.UUID `json:"address_id"`
	PhoneNumber string     `json:"phone_number"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier, arg.Name, arg.AddressID, arg.PhoneNumber)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AddressID,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSupplier = `-- name: DeleteSupplier :exec
DELETE FROM supplier
WHERE id = $1
`

func (q *Queries) DeleteSupplier(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSupplier, id)
	return err
}

const getAllSuppliers = `-- name: GetAllSuppliers :many
SELECT id, name, address_id, phone_number, created_at, updated_at from supplier
ORDER BY name ASC
`

func (q *Queries) GetAllSuppliers(ctx context.Context) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, getAllSuppliers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AddressID,
			&i.PhoneNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupplierByID = `-- name: GetSupplierByID :one
SELECT id, name, address_id, phone_number, created_at, updated_at from supplier
WHERE id = $1
`

func (q *Queries) GetSupplierByID(ctx context.Context, id uuid.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByID, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AddressID,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSupplierAddress = `-- name: UpdateSupplierAddress :one
UPDATE supplier
SET address_id = $2
WHERE id = $1
RETURNING id, name, address_id, phone_number, created_at, updated_at
`

type UpdateSupplierAddressParams struct {
	ID        uuid.UUID `json:"id"`
	AddressID uuid.UUID `json:"address_id"`
}

func (q *Queries) UpdateSupplierAddress(ctx context.Context, arg UpdateSupplierAddressParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, updateSupplierAddress, arg.ID, arg.AddressID)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AddressID,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
